server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:8080/my_project
    username: root
    password: Ritik@2310
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
